"""
Django settings for fitness project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STRIPE_PUBLIC_KEY = "pk_test_51R2KMYHDs0hWtDE4feSOKRz4NHYUFSnPp3Roe01vwf8E4Sjv7HxWTbznmvlsMMoy5ecFct2AgS9bf4u03nO8NbO200S3MPNMNw"
STRIPE_SECRET_KEY = "sk_test_51R2KMYHDs0hWtDE46vPjchKdunyjlc3Btlqni2lHtLT1Ub9xqzKihvAnvBhTsKzLiRLuYSEHuNXXVJlf7TzNbmhl00exo4Zhsh"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!o^s#$x+=hefar-^78*!in0+dhv4uxq2!^dgwk1o+moplq#n76'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
# ]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'workouts',
    'users',
    'crispy_forms',
    'fitness',
    'storages',
    'uploads',
#   'django_dynamodb_sessions',
    #'django_dynamodb_engine',
   
]

AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']
LOGIN_REDIRECT_URL = 'workout-list'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = '/'


MEDIA_URL = '/media/'
# Collect static files into S3
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_ROOT = BASE_DIR / 'media'
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',  # This tells Django to look for static files in the static/ folder
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fitness.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Ensure global templates are included
        'APP_DIRS': True,  # Important: Ensures templates in each app's `templates/` folder are found
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fitness.wsgi.application'

CSRF_TRUSTED_ORIGINS = [
    'https://5ef2e812ae8a41aab74f0b9f83087e08.vfs.cloud9.us-east-1.amazonaws.com'
]

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# INSTALLED_APPS = [
#     # Other installed apps
#     'django_dynamodb_engine',
# ]

# Database connection settings for DynamoDB
# DATABASES = {
#     'default': {
#         'ENGINE': 'django_dynamodb_engine',
#         'NAME': 'django-sessions',  # The name of your DynamoDB table
#         'AWS_ACCESS_KEY_ID': 'ASIARZNDPJ4NL6TCWAOL',
#         'AWS_SECRET_ACCESS_KEY': '96rXOWFFrZJqmY22WlD4Dce5QUdmuL6db3TONWmV',
#         'AWS_REGION': 'us-east-1',  # Set the region for DynamoDB
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Or another supported backend
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

import boto3

# Force boto3 to use explicit credentials globally
boto3.setup_default_session(
    aws_access_key_id='ASIARZNDPJ4NL6TCWAOL',
    aws_secret_access_key='96rXOWFFrZJqmY22WlD4Dce5QUdmuL6db3TONWmV',
    region_name='us-east-1'
)

# AWS S3 Storage Configuration
AWS_ACCESS_KEY_ID = 'ASIARZNDPJ4NL6TCWAOL'
AWS_SECRET_ACCESS_KEY = '96rXOWFFrZJqmY22WlD4Dce5QUdmuL6db3TONWmV'
AWS_STORAGE_BUCKET_NAME = 'fitness-ap-dataset'
AWS_S3_REGION_NAME = 'us-east-1'

# Use S3 for static and media files
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/media/'
STATIC_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/static/'


# AWS_ACCESS_KEY_ID = 'ASIARZNDPJ4NL6TCWAOL'
# AWS_SECRET_ACCESS_KEY = '96rXOWFFrZJqmY22WlD4Dce5QUdmuL6db3TONWmV'
# AWS_REGION='us-east-1'  # Set the region for DynamoDB
# SESSION_ENGINE = 'django_dynamodb_sessions.backends.dynamodb'
# settings.py

# SESSION_ENGINE = 'django_dynamodb_sessions.backends.dynamodb'
  # Default backend for session storage using the database


# DYNAMODB_SESSIONS_TABLE_NAME = 'django-sessions'
# DYNAMODB_SESSIONS_REGION = 'us-east-1' # change region name
# # Add this line to use S3 storage for static files
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# # Define STATIC_ROOT to avoid Django errors
# STATIC_ROOT = BASE_DIR / 'staticfiles'  
# # # # AWS S3 Settings

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Ensure a local folder for collectstatic
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# AWS_STORAGE_BUCKET_NAME = 'fitness-ap-dataset'
# AWS_S3_REGION_NAME = 'us-east-1'  # Example: 'us-east-1'
# AWS_S3_ACCESS_KEY_ID = 'ASIARZNDPJ4NL6TCWAOL'
# AWS_S3_SECRET_ACCESS_KEY = '96rXOWFFrZJqmY22WlD4Dce5QUdmuL6db3TONWmV'
# AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'

# # # # Use S3 for static files
# STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'

# # # # Use S3 for media files
# # DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'

# # Static files settings
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
CSRF_TRUSTED_ORIGINS = ['https://5ef2e812ae8a41aab74f0b9f83087e08.vfs.cloud9.us-east-1.amazonaws.com']

# Security settings for Cloud9
ALLOWED_HOSTS = ['5ef2e812ae8a41aab74f0b9f83087e08.vfs.cloud9.us-east-1.amazonaws.com', 'localhost', '127.0.0.1','44.200.210.43']
 # Allows access from all domains, modify as needed
# Use S3 for media and static files
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# settings.py
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # or os.path.join(BASE_DIR, 'static')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


 # default fallback
