# Generated by Django 5.1.6 on 2025-02-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='name',
        ),
        migrations.AddField(
            model_name='workout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-02-22 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='title',
            field=models.CharField(default='2025-02-22 00:00:00', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workout',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workouts/'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
